version: '3.7'
services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
      interval: 5s
      timeout: 3s
      retries: 5
  migrate:
    image: migrate/migrate
    env_file:
      - .env
    volumes:
      - ./db/migrations:/db/migrations
    command:
      [
        '-path',
        '/db/migrations',
        '-database',
        'postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@db:5432/$POSTGRES_DB?sslmode=disable',
        'up'
      ]
    depends_on:
      db:
        condition: service_healthy
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default
    ports:
      - '8080:8080'
volumes:
  data:
